const BooksData = [
  {
    id: 1,
    title: "Clean Code",
    author: "Robert C. Martin",
    isbn: "9780132350884",
    category: "Software Engineering",
    total_copies: 10,
    available_copies: 4,
  },
  {
    id: 2,
    title: "The Pragmatic Programmer",
    author: "Andrew Hunt",
    isbn: "9780201616224",
    category: "Programming",
    total_copies: 7,
    available_copies: 2,
  },
  {
    id: 3,
    title: "Design Patterns: Elements of Reusable Object-Oriented Software",
    author: "Erich Gamma, Richard Helm, Ralph Johnson, John Vlissides",
    isbn: "9780201633610",
    category: "Software Engineering",
    total_copies: 8,
    available_copies: 3,
  },
  {
    id: 4,
    title: "Introduction to Algorithms",
    author:
      "Thomas H. Cormen, Charles E. Leiserson, Ronald L. Rivest, Clifford Stein",
    isbn: "9780262033848",
    category: "Computer Science",
    total_copies: 12,
    available_copies: 5,
  },
  {
    id: 5,
    title: "The Mythical Man-Month",
    author: "Frederick P. Brooks Jr.",
    isbn: "9780201835953",
    category: "Software Engineering",
    total_copies: 6,
    available_copies: 1,
  },
  {
    id: 6,
    title: "Code Complete",
    author: "Steve McConnell",
    isbn: "9780735619678",
    category: "Programming",
    total_copies: 9,
    available_copies: 6,
  },
  {
    id: 7,
    title: "Structure and Interpretation of Computer Programs",
    author: "Harold Abelson, Gerald Jay Sussman, Julie Sussman",
    isbn: "9780262510875",
    category: "Computer Science",
    total_copies: 5,
    available_copies: 2,
  },
  {
    id: 8,
    title: "Refactoring: Improving the Design of Existing Code",
    author: "Martin Fowler",
    isbn: "9780201485677",
    category: "Software Engineering",
    total_copies: 7,
    available_copies: 4,
  },
  {
    id: 9,
    title: "Artificial Intelligence: A Modern Approach",
    author: "Stuart Russell, Peter Norvig",
    isbn: "9780136042594",
    category: "Artificial Intelligence",
    total_copies: 10,
    available_copies: 7,
  },
  {
    id: 10,
    title: "The Clean Coder",
    author: "Robert C. Martin",
    isbn: "9780137081073",
    category: "Software Engineering",
    total_copies: 6,
    available_copies: 3,
  },
];
export default BooksData;
