
const StudentsData = [
   {
    id: 1,
    name: "Alice Johnson",
    roll_number: "CSE2023001",
    department: "Computer Science",
    semester: "5",
    phone: "1234567890",
    email: "alice@example.com",
  },
  {
    id: 2,
    name: "Bob Smith",
    roll_number: "ECE2023002",
    department: "Electronics",
    semester: "4",
    phone: "0987654321",
    email: "bob@example.com",
  },
    {
    id: 3,
    name: "Carol Williams",
    roll_number: "ME2023003",
    department: "Mechanical Engineering",
    semester: "3",
    phone: "1122334455",
    email: "carol@example.com",
  },
  {
    id: 4,
    name: "David Brown",
    roll_number: "CE2023004",
    department: "Civil Engineering",
    semester: "6",
    phone: "5566778899",
    email: "david@example.com",
  },
  {
    id: 5,
    name: "Eva Davis",
    roll_number: "CSE2023005",
    department: "Computer Science",
    semester: "2",
    phone: "9988776655",
    email: "eva@example.com",
  },
  {
    id: 6,
    name: "Frank Wilson",
    roll_number: "ECE2023006",
    department: "Electronics",
    semester: "5",
    phone: "4433221100",
    email: "frank@example.com",
  },
  {
    id: 7,
    name: "Grace Taylor",
    roll_number: "ME2023007",
    department: "Mechanical Engineering",
    semester: "4",
    phone: "6677889900",
    email: "grace@example.com",
  },
  {
    id: 8,
    name: "Henry Martinez",
    roll_number: "CE2023008",
    department: "Civil Engineering",
    semester: "3",
    phone: "7788990011",
    email: "henry@example.com",
  },
  {
    id: 9,
    name: "Isabella Anderson",
    roll_number: "CSE2023009",
    department: "Computer Science",
    semester: "7",
    phone: "9900112233",
    email: "isabella@example.com",
  },
  {
    id: 10,
    name: "Jack Thomas",
    roll_number: "ECE2023010",
    department: "Electronics",
    semester: "6",
    phone: "3344556677",
    email: "jack@example.com",
  }
];
export default StudentsData;
