import { useEffect, useState } from "react";
import axios from "axios";

// eslint-disable-next-line
const rawData = [
  {
    id: 10,
    title: "Clean Code",
    author: "Robert C. Martin",
    available_copies: 4,
    total_copies: 10,
    price: "12.00",
    category: "Software Engineering",
    isbn: "392478548732982",
  },
  {
    id: 11,
    title: "The Pragmatic Programmer",
    author: "Andrew Hunt",
    available_copies: 3,
    total_copies: 8,
    price: "15.00",
    category: "Software Engineering",
    isbn: "9780201616224",
  },
  {
    id: 12,
    title: "Code Complete",
    author: "Steve McConnell",
    available_copies: 2,
    total_copies: 6,
    price: "18.50",
    category: "Software Engineering",
    isbn: "9780735619678",
  },
  {
    id: 13,
    title: "Introduction to Algorithms",
    author: "Thomas H. Cormen",
    available_copies: 1,
    total_copies: 5,
    price: "30.00",
    category: "Computer Science",
    isbn: "9780262033848",
  },
  {
    id: 14,
    title: "Design Patterns",
    author: "Erich Gamma",
    available_copies: 2,
    total_copies: 6,
    price: "22.99",
    category: "Software Engineering",
    isbn: "9780201633610",
  },
  {
    id: 15,
    title: "Refactoring",
    author: "Martin Fowler",
    available_copies: 5,
    total_copies: 10,
    price: "17.00",
    category: "Software Engineering",
    isbn: "9780201485677",
  },
  {
    id: 16,
    title: "You Don't Know JS",
    author: "Kyle Simpson",
    available_copies: 4,
    total_copies: 7,
    price: "10.00",
    category: "JavaScript",
    isbn: "392478548732982",
  },
  {
    id: 17,
    // eslint-disable-next-line no-script-url
    title: "JavaScript: The Good Parts",
    author: "Douglas Crockford",
    available_copies: 3,
    total_copies: 6,
    price: "8.99",
    category: "JavaScript",
    isbn: "9780596517748",
  },
  {
    id: 18,
    title: "Eloquent JavaScript",
    author: "Marijn Haverbeke",
    available_copies: 4,
    total_copies: 10,
    price: "11.50",
    category: "JavaScript",
    isbn: "9781593279509",
  },
  {
    id: 19,
    title: "Head First Design Patterns",
    author: "Eric Freeman",
    available_copies: 3,
    total_copies: 9,
    price: "19.99",
    category: "Software Engineering",
    isbn: "9780596007126",
  },
  {
    id: 20,
    title: "Cracking the Coding Interview",
    author: "Gayle Laakmann McDowell",
    available_copies: 2,
    total_copies: 7,
    price: "25.00",
    category: "Interview Preparation",
    isbn: "9780984782857",
  },
  {
    id: 21,
    title: "Artificial Intelligence: A Modern Approach",
    author: "Stuart Russell",
    available_copies: 1,
    total_copies: 4,
    price: "35.00",
    category: "AI",
    isbn: "9780136042594",
  },
  {
    id: 22,
    title: "Operating System Concepts",
    author: "Abraham Silberschatz",
    available_copies: 3,
    total_copies: 8,
    price: "28.00",
    category: "Operating Systems",
    isbn: "9781118063330",
  },
  {
    id: 23,
    title: "Computer Networks",
    author: "Andrew S. Tanenbaum",
    available_copies: 2,
    total_copies: 6,
    price: "24.00",
    category: "Networking",
    isbn: "9780132126953",
  },
  {
    id: 24,
    title: "The Mythical Man-Month",
    author: "Frederick P. Brooks Jr.",
    available_copies: 3,
    total_copies: 5,
    price: "16.00",
    category: "Software Engineering",
    isbn: "9780201835953",
  },
  {
    id: 25,
    title: "Structure and Interpretation of Computer Programs",
    author: "Harold Abelson",
    available_copies: 1,
    total_copies: 3,
    price: "21.00",
    category: "Computer Science",
    isbn: "9780262510875",
  },
  {
    id: 26,
    title: "Agile Software Development",
    author: "Robert C. Martin",
    available_copies: 4,
    total_copies: 7,
    price: "20.00",
    category: "Agile",
    isbn: "9780135974445",
  },
  {
    id: 27,
    title: "Continuous Delivery",
    author: "Jez Humble",
    available_copies: 2,
    total_copies: 5,
    price: "23.50",
    category: "DevOps",
    isbn: "9780321601919",
  },
  {
    id: 28,
    title: "Site Reliability Engineering",
    author: "Betsy Beyer",
    available_copies: 2,
    total_copies: 6,
    price: "27.00",
    category: "DevOps",
    isbn: "9781491929124",
  },
  {
    id: 29,
    title: "Designing Data-Intensive Applications",
    author: "Martin Kleppmann",
    available_copies: 3,
    total_copies: 7,
    price: "32.00",
    category: "Databases",
    isbn: "9781449373320",
  },
  {
    id: 30,
    title: "The Art of Computer Programming",
    author: "Donald E. Knuth",
    available_copies: 1,
    total_copies: 2,
    price: "40.00",
    category: "Algorithms",
    isbn: "9780201896831",
  },

  {
    id: 1,
    title: "Clean Code",
    author: "Robert C. Martin",
    isbn: "9780132350884",
    category: "Software Engineering",
    total_copies: 10,
    available_copies: 4,
  },
  {
    id: 2,
    title: "The Pragmatic Programmer",
    author: "Andrew Hunt",
    isbn: "9780201616224",
    category: "Programming",
    total_copies: 7,
    available_copies: 2,
  },
  {
    id: 3,
    title: "Design Patterns: Elements of Reusable Object-Oriented Software",
    author: "Erich Gamma, Richard Helm, Ralph Johnson, John Vlissides",
    isbn: "9780201633610",
    category: "Software Engineering",
    total_copies: 8,
    available_copies: 3,
  },
  {
    id: 4,
    title: "Introduction to Algorithms",
    author:
      "Thomas H. Cormen, Charles E. Leiserson, Ronald L. Rivest, Clifford Stein",
    isbn: "9780262033848",
    category: "Computer Science",
    total_copies: 12,
    available_copies: 5,
  },
  {
    id: 5,
    title: "The Mythical Man-Month",
    author: "Frederick P. Brooks Jr.",
    isbn: "9780201835953",
    category: "Software Engineering",
    total_copies: 6,
    available_copies: 1,
  },
  {
    id: 6,
    title: "Code Complete",
    author: "Steve McConnell",
    isbn: "9780735619678",
    category: "Programming",
    total_copies: 9,
    available_copies: 6,
  },
  {
    id: 7,
    title: "Structure and Interpretation of Computer Programs",
    author: "Harold Abelson, Gerald Jay Sussman, Julie Sussman",
    isbn: "9780262510875",
    category: "Computer Science",
    total_copies: 5,
    available_copies: 2,
  },
  {
    id: 8,
    title: "Refactoring: Improving the Design of Existing Code",
    author: "Martin Fowler",
    isbn: "9780201485677",
    category: "Software Engineering",
    total_copies: 7,
    available_copies: 4,
  },
  {
    id: 9,
    title: "Artificial Intelligence: A Modern Approach",
    author: "Stuart Russell, Peter Norvig",
    isbn: "9780136042594",
    category: "Artificial Intelligence",
    total_copies: 10,
    available_copies: 7,
  },
  {
    id: 10,
    title: "The Clean Coder",
    author: "Robert C. Martin",
    isbn: "9780137081073",
    category: "Software Engineering",
    total_copies: 6,
    available_copies: 3,
  },
];
export const useBooksData = () => {
  const [serverBooksData, setServerBooksData] = useState([]);

  useEffect(() => {
    axios
      .get(`${process.env.BACKEND_URL}/api/books/all`)
      .then((res) => setServerBooksData(res.data))
      .catch((err) => console.error(err));
  }, []); 

  return serverBooksData;
};
